name: dbt CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dbt for Postgres
        run: pip install "dbt-postgres>=1.11,<1.12"

      - name: Set up DBT profiles
        run: |
          mkdir -p ~/.dbt
          echo "my_project:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: ${{ secrets.DB_HOST }}
      port: ${{ secrets.DB_PORT }}
      user: ${{ secrets.DB_USER }}
      pass: ${{ secrets.DB_PASSWORD }}
      dbname: ${{ secrets.DB_NAME }}
      schema: ${{ secrets.DB_SCHEMA }}
  target: dev" > ~/.dbt/profiles.yml

      - name: Create raw_customers table
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -c "
          DROP TABLE IF EXISTS raw_customers;
          CREATE TABLE raw_customers (
              id INT,
              first_name TEXT,
              last_name TEXT,
              email TEXT
          );
          INSERT INTO raw_customers VALUES
              (1, 'Ali', 'Ahmadi', 'ali@test.com'),
              (2, 'Sara', 'Mohammadi', 'sara@test.com');
          "

      - name: Run dbt models
        run: dbt run --profiles-dir ~/.dbt

      - name: Run dbt tests
        run: dbt test --profiles-dir ~/.dbt
